//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marketentityproc
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int kullanicino { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string mail { get; set; }
        public string telefon { get; set; }
    }
}
